import { useRef } from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface InfographicData {
  title: string;
  subtitle: string;
  sections: Array<{ heading: string; points: string[] }>;
  keyStat: string;
  bottomLine: string;
}

const SECTION_COLORS = [
  "bg-blue-50 border-blue-200 dark:bg-blue-950/30 dark:border-blue-800",
  "bg-purple-50 border-purple-200 dark:bg-purple-950/30 dark:border-purple-800",
  "bg-emerald-50 border-emerald-200 dark:bg-emerald-950/30 dark:border-emerald-800",
  "bg-amber-50 border-amber-200 dark:bg-amber-950/30 dark:border-amber-800",
];

const ICON_COLORS = ["text-blue-500", "text-purple-500", "text-emerald-500", "text-amber-500"];

const SECTION_ICONS = ["📌", "💡", "🔍", "🎯"];

export function InfographicView({ data }: { data: InfographicData }) {
  const ref = useRef<HTMLDivElement>(null);

  const handleCopy = async () => {
    if (!ref.current) return;
    try {
      const { default: html2canvas } = await import("html2canvas");
      const canvas = await html2canvas(ref.current, { scale: 2, backgroundColor: "#ffffff" });
      canvas.toBlob(blob => {
        if (blob) {
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = "recall-infographic.png";
          a.click();
          URL.revokeObjectURL(url);
        }
      });
    } catch {
      // html2canvas not installed — show text fallback
      alert("Install html2canvas to enable image download.");
    }
  };

  return (
    <div className="space-y-3">
      <div className="flex justify-end">
        <Button variant="outline" size="sm" onClick={handleCopy} className="gap-2">
          <Download className="h-3.5 w-3.5" /> Save as Image
        </Button>
      </div>

      <div ref={ref} className="rounded-2xl overflow-hidden border border-border bg-white dark:bg-gray-950 shadow-lg">
        {/* Header */}
        <div className="bg-gradient-to-br from-indigo-600 to-purple-700 p-8 text-white text-center">
          <h2 className="text-2xl font-extrabold leading-tight mb-2">{data.title}</h2>
          <p className="text-indigo-200 text-sm leading-relaxed max-w-md mx-auto">{data.subtitle}</p>
        </div>

        {/* Key Stat */}
        {data.keyStat && (
          <div className="bg-amber-50 dark:bg-amber-950/30 border-b border-amber-200 dark:border-amber-800 px-6 py-5 text-center">
            <p className="text-xs font-bold text-amber-600 uppercase tracking-widest mb-1">Key Insight</p>
            <p className="text-xl font-bold text-amber-900 dark:text-amber-300 leading-snug">{data.keyStat}</p>
          </div>
        )}

        {/* Sections grid */}
        <div className="grid sm:grid-cols-2 gap-px bg-border">
          {data.sections.map((section, i) => (
            <div key={i} className={`p-5 ${SECTION_COLORS[i % SECTION_COLORS.length]} bg-white dark:bg-gray-950`}>
              <div className="flex items-center gap-2 mb-3">
                <span className="text-lg">{SECTION_ICONS[i % SECTION_ICONS.length]}</span>
                <h3 className={`text-sm font-bold uppercase tracking-wide ${ICON_COLORS[i % ICON_COLORS.length]}`}>
                  {section.heading}
                </h3>
              </div>
              <ul className="space-y-1.5">
                {section.points.map((pt, j) => (
                  <li key={j} className="flex items-start gap-2 text-sm text-foreground/80 leading-snug">
                    <span className="text-primary mt-0.5 shrink-0">•</span>
                    {pt}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Bottom line */}
        {data.bottomLine && (
          <div className="bg-gray-900 dark:bg-gray-800 px-6 py-4 text-center">
            <p className="text-white text-sm font-medium italic">"{data.bottomLine}"</p>
            <p className="text-gray-400 text-xs mt-1">Generated by Recall.ai</p>
          </div>
        )}
      </div>
    </div>
  );
}
